# Generated by Django 3.1.2 on 2020-11-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
